In [1]:
import pandas as pd
import numpy as np

In [2]:
# pd.Series: 一次元配列のnumpyにインデックスというラベルが付けられたようなクラスオブジェクト
# ラベルとラベルに紐付いたデータ配列が吐かれる
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [3]:
# 値のみ抽出
obj.values

array([ 4,  7, -5,  3])

In [4]:
# インデックスのみ抽出
obj.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
# インデックスに文字列を指定することもできる
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [6]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [7]:
obj2['a']

-5

In [8]:
# インデックスを指定して対応した値を代入
obj2['d'] = 6
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [9]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [10]:
# 0より大きい値を抽出
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [11]:
# 全ての値に2を掛ける
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [12]:
# 全ての要素にexpする
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [13]:
# ラベルbがあるか判定
'b' in obj2

True

In [14]:
# ラベルeがあるか判定
'e' in obj2

False

In [15]:
# Seriesはディクショナリで指定することができる
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [16]:
# indexを指定すると対応したSeriesを用意してくれる
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [17]:
# NA値かどうかを判定する
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [18]:
# NA値ではないかを判定する
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [19]:
# インスタンスメソッドとしても使える
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [20]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [21]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [22]:
# Seriesの算術演算はNA値があるインデックスの値はNAになる
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [23]:
# Seriesに名前を付けたり、indexに名前をつけることができる
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [24]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [25]:
# あとからindexを代入することができる
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [26]:
# pd.DataFrame: Seriesを複数に束ねたようなオブジェクト
# 配列のディクショナリを渡す
data = {
    'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
    'year': [2000, 2001, 2001, 2001, 2002],
    'pop': [1.5, 1.7, 3.6, 2.4, 2.9]
}
frame = pd.DataFrame(data)
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2001
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [27]:
# 列の順番をcolumnsで指定できる
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2001    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [28]:
# indexを指定できる
# columnsに存在しない名前を渡すと列を自動に作ってくれる
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], index=['one', 'two', 'three', 'four', 'five'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2001    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [29]:
# カラムの一覧を得る
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [30]:
# カラムを指定してSeriesを得る
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [31]:
# インスタンスメソッドの形式でもカラムを指定してSeriesを得る
frame2.year

one      2000
two      2001
three    2001
four     2001
five     2002
Name: year, dtype: int64

In [35]:
# 行を指定して列の一覧を得る
frame2.loc['three']

year     2001
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [36]:
# 列を指定して代入できる
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2001    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [37]:
# 式展開で代入もできる
frame2['debt'] = np.arange(5.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2001    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [38]:
# 列にSeriesを代入できる
# Seriesにないカラムの場合はNAが入る
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2001    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [39]:
# 存在しない列に代入を行うと新しい列が生成される
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2001    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False

In [40]:
# delキーワードで列を消すことができる（ディクショナリと同じ）
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [42]:
# ネストしたディクショナリの場合を考える
# 外側のキーが列のインデックスになり、内側のキーが行のインデックスとして解釈される
pop = {'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [43]:
# 転置できる
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [44]:
# pop = {'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
# indexを指定してソートできる
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [45]:
pdata = {'Ohio': frame3['Ohio'][:-1], 'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [46]:
# データフレームのインデックスや列のインデックスは名前を持てる
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [47]:
# values属性を参照する
frame3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [48]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2001, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

In [49]:
# インデックスの指定
obj = pd.Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [50]:
# スライスできる
index[1:]

Index(['b', 'c'], dtype='object')

In [51]:
# indexオブジェクトはイミュータブルなのでこのような比較も安全にできる
index = pd.Index(np.arange(3))
obj2 = pd.Series([1.5, -2.5, 0], index=index)
obj2.index is index

True

In [52]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [53]:
# 指定したカラムを持っているかを確認する
'Ohio' in frame3.columns

True

In [54]:
2003 in frame3.index

False