In [1]:
import numpy as np

In [2]:
x = np.array([[1., 2., 3.], [4, 5, 6]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [3]:
x

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [4]:
y

array([[  6.,  23.],
       [ -1.,   7.],
       [  8.,   9.]])

In [5]:
# 内積
# (2, 3) . (3, 2) = (2, 2)
x.dot(y)

array([[  28.,   64.],
       [  67.,  181.]])

In [6]:
# 内積
# (2, 3) . (3, 1) = (2, 1)
np.dot(x, np.ones(3))

array([  6.,  15.])

In [7]:
from numpy.linalg import inv, qr


X = np.random.randn(5, 5)
mat = X.T.dot(X)
mat

array([[ 9.30175689, -0.9891074 , -0.35745401, -4.54883831, -2.14574044],
       [-0.9891074 ,  6.87315086,  2.57448106,  5.17903781, -2.05081521],
       [-0.35745401,  2.57448106,  2.47407546,  1.67237017, -1.28438895],
       [-4.54883831,  5.17903781,  1.67237017,  8.57000607, -0.23330462],
       [-2.14574044, -2.05081521, -1.28438895, -0.23330462,  2.49091984]])

In [8]:
# 正方行列に対して逆行列を返す
inv(mat)

array([[ 0.21999817, -0.02769803,  0.09755248,  0.12068927,  0.2283125 ],
       [-0.02769803,  0.49588608, -0.20909683, -0.26672289,  0.25161331],
       [ 0.09755248, -0.20909683,  0.77551938,  0.03538199,  0.31507503],
       [ 0.12068927, -0.26672289,  0.03538199,  0.33322642, -0.06617797],
       [ 0.2283125 ,  0.25161331,  0.31507503, -0.06617797,  0.96155284]])

In [9]:
# 正方行列と逆行列の性質を確認
# 単位行列が得られる
mat.dot(inv(mat))

array([[  1.00000000e+00,   0.00000000e+00,  -1.11022302e-16,
         -1.11022302e-16,   0.00000000e+00],
       [ -1.66533454e-16,   1.00000000e+00,   0.00000000e+00,
         -1.38777878e-16,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
         -1.38777878e-17,   0.00000000e+00],
       [  1.94289029e-16,  -2.63677968e-16,   1.66533454e-16,
          1.00000000e+00,  -4.16333634e-16],
       [  0.00000000e+00,  -1.11022302e-16,  -1.11022302e-16,
          1.38777878e-16,   1.00000000e+00]])

In [10]:
# QR分解する
# 直交行列と上三角行列が得られる
q, r = qr(mat)
r

array([[-10.62661377,   3.3949731 ,   1.09227014,   8.14140523,
          2.04723465],
       [  0.        ,  -8.62258211,  -3.71175387,  -7.14682455,
          3.31070735],
       [  0.        ,   0.        ,  -1.53397574,   1.10242025,
          0.80023472],
       [  0.        ,   0.        ,   0.        ,  -2.28816719,  -0.2282703 ],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.93508125]])