In [1]:
import numpy as np

In [2]:
x = np.array([[1., 2., 3.], [4, 5, 6]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [3]:
x

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [4]:
y

array([[  6.,  23.],
       [ -1.,   7.],
       [  8.,   9.]])

In [5]:
x.dot(y)

array([[  28.,   64.],
       [  67.,  181.]])

In [6]:
np.dot(x, np.ones(3))

array([  6.,  15.])

In [8]:
from numpy.linalg import inv, qr


X = np.random.randn(5, 5)
mat = X.T.dot(X)
inv(mat)

array([[  587.99086008,   -76.32400071,  -613.62291634,  -307.6476109 ,
         -851.79904733],
       [  -76.32400071,    10.30221765,    79.59354365,    39.70598239,
          109.90566467],
       [ -613.62291634,    79.59354365,   643.26558652,   321.83681944,
          893.66677276],
       [ -307.6476109 ,    39.70598239,   321.83681944,   161.89947626,
          447.58765501],
       [ -851.79904733,   109.90566467,   893.66677276,   447.58765501,
         1243.18329787]])

In [9]:
mat.dot(inv(mat))

array([[  1.00000000e+00,  -4.97379915e-14,   1.70530257e-13,
         -1.70530257e-13,  -1.13686838e-13],
       [ -4.54747351e-13,   1.00000000e+00,   4.54747351e-13,
          2.27373675e-13,   4.54747351e-13],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,  -4.26325641e-14,   0.00000000e+00,
          1.00000000e+00,   0.00000000e+00],
       [  2.27373675e-13,  -2.84217094e-14,  -2.27373675e-13,
         -1.13686838e-13,   1.00000000e+00]])

In [10]:
q, r = qr(mat)
r

array([[ -1.48403252e+00,   2.76913006e+00,  -4.90861975e+00,
         -2.70455210e+00,   3.24092939e+00],
       [  0.00000000e+00,  -6.85640311e+00,   5.23347702e+00,
          5.50438469e-01,  -3.35431431e+00],
       [  0.00000000e+00,   0.00000000e+00,  -9.60627437e-01,
          6.64637040e-01,   4.51582054e-01],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         -9.73492478e-01,   3.50862756e-01],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   5.51979226e-04]])