In [1]:
import numpy as np

# ndarray: N-dimensional array
# ndarrayを生成/操作する
# 一番簡単な精製方法はpythonのlistを渡すこと
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [2]:
# 要素のデータ型はこれ
arr1.dtype

dtype('float64')

In [3]:
# ネスト内の要素数が同じであればndarrayは多次元配列を返す
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
# ネストの階層の深さ(次元数)はこれ
arr2.ndim

2

In [5]:
# 配列次元数のとそのサイズはこれ
arr2.shape

(2, 4)

In [6]:
arr2.dtype

dtype('int64')

In [7]:
# 指定したサイズの0埋めndarrayを生成する
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [8]:
np.zeros((3, 6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [9]:
# 配列の生成速度が若干高速になることがあるため、値を0や1で初期化する必要のない場合はnp.emptyをzerosの代わりに使う
np.empty((2, 3, 2))

array([[[  6.91564596e-310,   2.49795559e-316],
        [  1.58101007e-322,   3.95252517e-322],
        [  2.37151510e-322,   3.16202013e-322]],

       [[  0.00000000e+000,   6.91563750e-310],
        [  6.91563750e-310,   6.91563750e-310],
        [  6.91563750e-310,   6.91563750e-310]]])

In [10]:
# 等間隔に増減させた値で要素を満たしてくれる関数
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
# データ型を指定する
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1

array([ 1.,  2.,  3.])

In [12]:
arr1.dtype

dtype('float64')

In [13]:
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2

array([1, 2, 3], dtype=int32)

In [14]:
arr2.dtype

dtype('int32')

In [15]:
arr = np.array([1, 2, 3, 4, 5])

In [16]:
arr.dtype

dtype('int64')

In [17]:
# ndarrayのデータ型を変更するにはastypeを使う
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [18]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([  3.7,  -1.2,  -2.6,   0.5,  12.9,  10.1])

In [19]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [20]:
numeric_strings = np.array(['1.25', '-9.6', '42'])
numeric_strings

array(['1.25', '-9.6', '42'],
      dtype='<U4')

In [21]:
numeric_strings.astype(float)

array([  1.25,  -9.6 ,  42.  ])

In [22]:
int_array = np.arange(10)
# float64を指定しなくてもfloat64になるが、あえて明示的に指定する
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
# int64をfloat64に変換する
int_array.astype(calibers.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [23]:
# 型名ではなく型コード名でも指定できる
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [24]:
# ndarrayとスカラーの計算
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [25]:
# 同じサイズのndarray同士の算術演算は同じ位置の要素同士で計算される
arr * arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [26]:
1 / arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [27]:
arr ** 0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

In [28]:
# インデックス参照とスライシングをしていく
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
# インデックスを参照する
arr[5]

5

In [30]:
# スライシング: ndarrayからndarrayを一部切り出すこと
# スライシングをする
arr[5:8]

array([5, 6, 7])

In [31]:
# スライスはもとのndarrayのポインタを指してるので、スライスに対する変更はオリジナルに対する変更になる
# スライスをndarrayの実コピーとして生成する場合には、明示的にarr[5:8].copy()とすること
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [32]:
arr_slice = arr[5:8]
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [33]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [34]:
# 二次元以上の配列の場合、インデックス参照の手段が増える
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [35]:
arr2d[0][2]

3

In [36]:
arr2d[0, 2]

3

In [37]:
# 3次元の場合
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [38]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [40]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [41]:
arr3d[1, 0]

array([7, 8, 9])

In [42]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [43]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [46]:
arr2d[1, :2]

array([4, 5])

In [47]:
arr2d[2, :1]

array([7])

In [48]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [49]:
arr2d[:2, 1:] = 0

In [50]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [51]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [52]:
data = np.random.randn(7, 4)

In [53]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'],
      dtype='<U4')

In [54]:
data

array([[-0.6967998 , -1.76590477, -2.66462624,  1.54493727],
       [ 0.14802834, -1.08952711,  0.67895451, -1.14721987],
       [-0.3598017 , -0.45210187,  1.23272923, -1.68430009],
       [ 0.25096305, -0.14627509, -0.79203445,  1.35234285],
       [ 0.70144817, -1.3685473 , -0.76574179, -0.89060402],
       [ 0.80496258, -1.28373502,  1.67779451,  1.01535668],
       [-2.20463229, -1.75397617, -1.0530192 , -0.33317413]])

In [55]:
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [56]:
data[names == 'Bob']

array([[-0.6967998 , -1.76590477, -2.66462624,  1.54493727],
       [ 0.25096305, -0.14627509, -0.79203445,  1.35234285]])

In [57]:
data[names == 'Bob', 2:]

array([[-2.66462624,  1.54493727],
       [-0.79203445,  1.35234285]])

In [58]:
data[names == 'Bob', 3]

array([ 1.54493727,  1.35234285])

In [59]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True], dtype=bool)

In [60]:
data[(names != 'Bob')]

array([[ 0.14802834, -1.08952711,  0.67895451, -1.14721987],
       [-0.3598017 , -0.45210187,  1.23272923, -1.68430009],
       [ 0.70144817, -1.3685473 , -0.76574179, -0.89060402],
       [ 0.80496258, -1.28373502,  1.67779451,  1.01535668],
       [-2.20463229, -1.75397617, -1.0530192 , -0.33317413]])

In [61]:
mask = (names == 'Bob') | (names == 'Will')

In [62]:
mask

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [63]:
data[mask]

array([[-0.6967998 , -1.76590477, -2.66462624,  1.54493727],
       [-0.3598017 , -0.45210187,  1.23272923, -1.68430009],
       [ 0.25096305, -0.14627509, -0.79203445,  1.35234285],
       [ 0.70144817, -1.3685473 , -0.76574179, -0.89060402]])

In [64]:
data[data < 0] = 0

In [65]:
data

array([[ 0.        ,  0.        ,  0.        ,  1.54493727],
       [ 0.14802834,  0.        ,  0.67895451,  0.        ],
       [ 0.        ,  0.        ,  1.23272923,  0.        ],
       [ 0.25096305,  0.        ,  0.        ,  1.35234285],
       [ 0.70144817,  0.        ,  0.        ,  0.        ],
       [ 0.80496258,  0.        ,  1.67779451,  1.01535668],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [66]:
data[names != 'Joe'] = 7

In [67]:
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.14802834,  0.        ,  0.67895451,  0.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.80496258,  0.        ,  1.67779451,  1.01535668],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [68]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [69]:
arr[[4, 3, 0, 6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [70]:
arr[[-3, -5, -7]]

array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

In [71]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [72]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [74]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [75]:
arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [77]:
arr = np.arange(15).reshape((3, 5))

In [78]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [79]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [80]:
arr = np.random.randn(6, 3)
np.dot(arr.T, arr)

array([[ 3.03295275, -1.56872378,  1.53013862],
       [-1.56872378,  2.13831121, -1.85628914],
       [ 1.53013862, -1.85628914,  2.57138546]])

In [81]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [83]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [84]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [85]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])