In [42]:
import numpy as np

# ndarray: N-dimensional array
# ndarrayを生成/操作する
# 一番簡単な精製方法はpythonのlistを渡すこと
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [ ]:
# 要素のデータ型はこれ
arr1.dtype

In [43]:
# ネスト内の要素数が同じであればndarrayは多次元配列を返す
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [44]:
# ネストの階層の深さ(次元数)はこれ
arr2.ndim

2

In [45]:
# 配列次元数のとそのサイズはこれ
arr2.shape

(2, 4)

In [47]:
arr2.dtype

dtype('int64')

In [48]:
# 指定したサイズの0埋めndarrayを生成する
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [49]:
np.zeros((3, 6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [50]:
# 配列の生成速度が若干高速になることがあるため、値を0や1で初期化する必要のない場合はnp.emptyをzerosの代わりに使う
np.empty((2, 3, 2))

array([[[  2.09879086e-316,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000]],

       [[  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000]]])

In [51]:
# 等間隔に増減させた値で要素を満たしてくれる関数
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [53]:
# データ型を指定する
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1

array([ 1.,  2.,  3.])

In [ ]:
arr1.dtype

In [54]:
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2

array([1, 2, 3], dtype=int32)

In [55]:
arr2.dtype

dtype('int32')

In [56]:
arr = np.array([1, 2, 3, 4, 5])

In [57]:
arr.dtype

dtype('int64')

In [58]:
# ndarrayのデータ型を変更するにはastypeを使う
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [59]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([  3.7,  -1.2,  -2.6,   0.5,  12.9,  10.1])

In [60]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [75]:
numeric_strings = np.array(['1.25', '-9.6', '42'])
numeric_strings

array(['1.25', '-9.6', '42'],
      dtype='<U4')

In [76]:
numeric_strings.astype(float)

array([  1.25,  -9.6 ,  42.  ])

In [93]:
int_array = np.arange(10)
# float64を指定しなくてもfloat64になるが、あえて明示的に指定する
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
# int64をfloat64に変換する
int_array.astype(calibers.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [94]:
# 型名ではなく型コード名でも指定できる
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [100]:
# ndarrayとスカラーの計算
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [102]:
# 同じサイズのndarray同士の算術演算は同じ位置の要素同士で計算される
arr * arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [97]:
1 / arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [98]:
arr ** 0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

In [119]:
# インデックス参照とスライシングをしていく
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [120]:
# インデックスを参照する
arr[5]

5

In [121]:
# スライシング: ndarrayからndarrayを一部切り出すこと
# スライシングをする
arr[5:8]

array([5, 6, 7])

In [123]:
# スライスはもとのndarrayのポインタを指してるので、スライスに対する変更はオリジナルに対する変更になる
# スライスをndarrayの実コピーとして生成する場合には、明示的にarr[5:8].copy()とすること
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [124]:
arr_slice = arr[5:8]
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [125]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [126]:
# 二次元以上の配列の場合、インデックス参照の手段が増える
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [127]:
arr2d[2][0]

7

In [ ]:
# 3次元の場合
