In [2]:
import numpy as np

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# 要素ごとにsqrtする
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [5]:
# 要素ごとにexpする
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [6]:
x = np.random.randn(8)
y = np.random.randn(8)

In [7]:
x

array([ 0.12475618, -2.48334485,  2.04570125,  0.92973183,  1.3341985 ,
        1.50829611,  0.50046877, -1.05464671])

In [8]:
y

array([ 0.56806266,  0.2655344 , -0.81027   ,  2.23852932,  1.07857398,
        1.13750393, -0.18299069,  1.32404276])

In [9]:
# 同じ次元のndarrayの要素を比較して大きい方を返す
np.maximum(x, y)

array([ 0.56806266,  0.2655344 ,  2.04570125,  2.23852932,  1.3341985 ,
        1.50829611,  0.50046877,  1.32404276])

In [10]:
# 正規分布からランダムに抽出して要素を5倍にする
arr = np.random.randn(7) * 5

In [11]:
np.modf(arr)

(array([ 0.84433113,  0.46897938, -0.07803671, -0.55473752,  0.24574007,
         0.51195153, -0.76679879]),
 array([  3.,   0., -14.,  -9.,   6.,   6.,  -0.]))